id: A52BD1455
title: Prayer to the Lineage of the Supreme Hayagrīva Emanation from the Aural Transmission
type: translation
pechas:
- IC44E9729
- IBA4132B4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:14:40.835814
  last_modified_at: 2023-01-04 12:14:40.835820
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IC44E9729/ACB7: 1BE5
  IBA4132B4/E2AE: 1BE5
